### ISSUE TITLE
Document/Visualize EVERYTHING.

### ISSUE THREAD

**Issue by RepComm** [RepComm/swbf_web_client#1]
Yuck, why is this guy just writing code without being visual for us common folk?
--
I'm far enough into this (terrain is displaying correctly, which is a HUGE milestone! of course there aren't any textures yet, but it's coming!) that I should start writting spiffy documentation for everything.

I want to make coming to the repository visual enough to inspire others to contribute (or at least think it's cool!), so I'm going to see about using github pages and/or a sub-site on my website for feed of the youtube videos and screenshots for people that don't like starring at large blocks of text..

**Comment by danielsfarm96** [comment]
This made me laugh, but I’m all about visual aids for common folk like myself!

**Comment by RepComm** [comment]
Sorry for the notification, I don't intend on spamming. I'm working on this right now, but I'm going to put it all up in one big load.
Plan:
Host a page on my site ( it needs some content right now anyways ), script it in such a way that it is like a feed of content (so I don't have to manually change the page's code to display the new things).
I'm going to implement it with twitter api, because I can upload to youtube/google photos/etc and/or post text and forward it all onto twitter, and then it will just magically appear on the page because of the way it's scripted up. I will probably want to rid myself of their yucky css, to match my style.
